[versions]
#build info
app-name = "Foundation"
app-description = "Foundational KMP Compose project provided by Bridge Supplies."
app-copyright = "© 2024 Bridge Supplies. All rights reserved."
app-vendor = "Bridge Supplies"
app-packageName = "bridge.supplies.foundation"
app-mainName = ".Foundation"
app-versionCode = "202405230"
app-versionName = "1.0.0"
android-minSdk = "28"
android-targetSdk = "34"
android-compileSdk = "34"
#packages
agp = "8.2.2"
junit = "4.13.2"
androidx-core-ktx = "1.13.1"
androidx-activity-compose = "1.9.0"
compose = "1.6.7"
compose-plugin = "1.6.10"
kotlin = "2.0.0"
kotlinx-datetime = "0.5.0"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization-json = "1.6.3"
lifecycle-viewmodel = "2.8.0"
koin = "3.6.0-alpha3"
koin-compose = "3.6.0-alpha3"
koin-compose-multiplatform = "1.2.0-alpha3"
navigation-compose = "2.7.0-alpha03"
chaintech-qrkit = "1.0.2"
g0dkar-qrcode-kotlin = "4.1.1"
androidx-datastore = "1.1.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle-viewmodel"}
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore"}
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-compose" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose-multiplatform" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }

chaintech-qrkit = { module = "network.chaintech:qr-kit", version.ref = "chaintech-qrkit" } # Android/iOS generation & scanning
g0dkar-qrcode-kotlin = { module = "io.github.g0dkar:qrcode-kotlin", version.ref = "g0dkar-qrcode-kotlin" } # Android/iOS/Desktop generation

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }